import type { Metadata } from "next";
import { Geist, Geist_Mono, Poetsen_One, Merienda } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poetsen = Poetsen_One({
  variable: "--font-poetsen",
  subsets: ["latin"],
  weight: "400",
});

const merienda = Merienda({
  variable: "--font-merienda",
  subsets: ["latin"],
  weight: "400",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poetsen.variable} ${merienda.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
